name: Build Packer Image

on:
  push:
    branches:
      - packer-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Packer Init
      run: packer init .
    - name: Packer Fmt
      run: packer fmt .
    - name: Validate Packer template
      run: packer validate .
    - name: Build packer Image
      run: packer build .