name: Build Packer Image

on:
  push:
    branches:
      - packer-actions
env:
  CONFIG_DIRECTORY: "terraform"
jobs:
  launch:
    # needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout le code
      uses: actions/checkout@v2
    - name: Set up Terraform CLI
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.6
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Initialize Terraform
      run: |
        pwd      
        terraform init
        ls -a
      working-directory: ${{ env.CONFIG_DIRECTORY }}
    - name: Terraform apply
      run: |
        ls -a
        terraform apply -auto-approve
      working-directory: ${{ env.CONFIG_DIRECTORY }}